server:
    port: 8082
    servlet:
      context-path: /ui
    session:
      cookie:
        name: DUPA
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: swhr-users-client
      clientSecret: swhrSecret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/api/me
spring:
  thymeleaf:
    cache: false        